import type { Metadata } from "next";
import localFont from "next/font/local";
import {Nunito_Sans} from "next/font/google"
import "./globals.css";
import Navbar from "@/components/nav_components/Navbar";
import FloatingButton from "@/components/floating_button/FloatingButton";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const nunito_sans = Nunito_Sans({
  subsets:['latin'],
  weight:["200","300","400","500","600","700","800","900"],
  variable:"--font-nunito-sans"
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${nunito_sans.variable}`}>
        <div className="maxWidth">
        <Navbar/>
        {children}
        <FloatingButton/>
        </div>
      </body>
    </html>
  );
}
